stages:
  - build
  - test
  
build_job:
  stage: build
  script:
    - set MSBUILDDISABLENODEREUSE=1
    - ''
    - "Restoring NuGet Packages..."
    - '"c:\nuget\nuget.exe" restore "Queste.sln"'
    - "NuGet Packages restored"
    - ''
    - "Release build..."
    - '"C:\Program Files (x86)\MSBuild\14.0\Bin\msbuild.exe" /consoleloggerparameters:ErrorsOnly /maxcpucount /nologo /property:Configuration=Release /verbosity:quiet /m:4 /nr:false "Queste.sln"'
    - "Build completed"

test_job:
  stage: test
  script:
    - "Running Tests..."
    - '"C:\xunit\xunit.console.exe" ".\Queste.Test\bin\Release\Queste.Test.dll"'
    - "Tests complete"
    - ''
    - "Cleaning up Tests.."
    - DEL /Q ".\Queste.Test\bin"
    - "Tests cleaned"
  tags: 
  except:
    - tags